$browser = google-chrome-stable

$kbLock = Super+Alt, L
$kbRestoreLock = Super+Alt, L

$kbShowPanels = Super+Alt, K
$kbWindowFullscreen =  Super+Alt, F
$kbWindowBorderedFullscreen = Super, F

$cursorTheme = phinger-cursors-dark
$cursorSize = 48

