# CUSTOM KEYBINDINGS
exec = hyprctl dispatch submap global
submap = global

# window actions
bind = Super+Shift, h, movewindow, l
bind = Super+Shift, l, movewindow, r
bind = Super+Shift, k, movewindow, u
bind = Super+Shift, j, movewindow, d

bind = Super, h, movefocus, l
bind = Super, l, movefocus, r
bind = Super, k, movefocus, u
bind = Super, j, movefocus, d
bind = Super, TAB, exec, qs ipc -c overview call overview toggle

bindd = Super+Alt, J, $d toggle split, togglesplit

## Hyrpland general config
input {
    kb_layout = br,us
    kb_options =  grp:alt_space_toggle 

    numlock_by_default = false
    repeat_delay = 250
    repeat_rate = 35

    focus_on_close = 1

    touchpad {
        natural_scroll = yes
        disable_while_typing = true
        scroll_factor = 0.3
    }
}

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/workspaces.conf

# load plugins
source = ./plugins/dinamic-cursors.conf

gesture = 3, down,mod: alt,close
gesture = 3, horizontal, workspace
gesture = 3, swipe, mod: SUPER, resize
gesture = 3, pinch, fullscreen

exec-once= /usr/lib/polkit-kde-authentication-agent-1
exec-once = qs -c overview
exec-once = hyprpm reload -n
